"""create reconciliation schema

Revision ID: c99ac4d619c0
Revises: 
Create Date: 2026-08-28 04:08:25.417762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99ac4d619c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_records',
    sa.Column('ledger_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='amount_positive'),
    sa.PrimaryKeyConstraint('ledger_id')
    )
    op.create_index('ix_ledger_merchant_amount', 'ledger_records', ['merchant_id', 'amount'], unique=False)
    op.create_index('ix_ledger_merchant_date', 'ledger_records', ['merchant_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_ledger_records_merchant_id'), 'ledger_records', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_ledger_records_reference'), 'ledger_records', ['reference'], unique=False)
    op.create_index(op.f('ix_ledger_records_transaction_date'), 'ledger_records', ['transaction_date'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_run_id'), 'audit_events', ['run_id'], unique=False)
    op.create_table('settlement_records',
    sa.Column('settlement_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='amount_positive'),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('settlement_id')
    )
    op.create_index('ix_settlement_merchant_amount', 'settlement_records', ['merchant_id', 'amount'], unique=False)
    op.create_index('ix_settlement_merchant_date', 'settlement_records', ['merchant_id', 'settlement_date'], unique=False)
    op.create_index(op.f('ix_settlement_records_merchant_id'), 'settlement_records', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_settlement_records_reference'), 'settlement_records', ['reference'], unique=False)
    op.create_index(op.f('ix_settlement_records_settlement_date'), 'settlement_records', ['settlement_date'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='confidence_range'),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement_records.settlement_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'settlement_id', name='uq_match_result_run_settlement')
    )
    op.create_table('match_result_ledgers',
    sa.Column('match_result_id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledger_records.ledger_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_result_id', 'ledger_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_result_ledgers')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_settlement_records_settlement_date'), table_name='settlement_records')
    op.drop_index(op.f('ix_settlement_records_reference'), table_name='settlement_records')
    op.drop_index(op.f('ix_settlement_records_merchant_id'), table_name='settlement_records')
    op.drop_index('ix_settlement_merchant_date', table_name='settlement_records')
    op.drop_index('ix_settlement_merchant_amount', table_name='settlement_records')
    op.drop_table('settlement_records')
    op.drop_index(op.f('ix_audit_events_run_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_ledger_records_transaction_date'), table_name='ledger_records')
    op.drop_index(op.f('ix_ledger_records_reference'), table_name='ledger_records')
    op.drop_index(op.f('ix_ledger_records_merchant_id'), table_name='ledger_records')
    op.drop_index('ix_ledger_merchant_date', table_name='ledger_records')
    op.drop_index('ix_ledger_merchant_amount', table_name='ledger_records')
    op.drop_table('ledger_records')
    # ### end Alembic commands ###
